name: Compilar APK de Kivy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Configurar Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '11'

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Instalar dependencias de compilación
      run: |
        sudo apt-get update
        sudo apt-get install -y libltdl-dev libffi-dev libssl-dev python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libstdc++6 patch unzip

    - name: Instalar Buildozer y Cython
      run: |
        pip install --upgrade pip
        pip install cython buildozer

    - name: Instalar SDK y Herramientas previas
      run: |
        mkdir -p ~/.buildozer/android/platform/android-sdk
        cd ~/.buildozer/android/platform/android-sdk
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-6514223_latest.zip -O commandlinetools.zip
        unzip -q commandlinetools.zip
        mkdir -p cmdline-tools/latest
        mv bin lib cmdline-tools/latest/
        rm commandlinetools.zip
        yes | cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/.buildozer/android/platform/android-sdk --licenses

    - name: Compilar APK
      run: |
        buildozer -v android debug

    - name: Subir el APK generado
      uses: actions/upload-artifact@v4
      with:
        name: paquete-apk
        path: bin/*.apk
