name: Compilar APK de Kivy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Configurar Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '11'

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Instalar dependencias de compilación
      run: |
        sudo apt-get update
        sudo apt-get install -y libltdl-dev libffi-dev libssl-dev python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libstdc++6 patch unzip

    - name: Instalar Buildozer y Cython
      run: |
        pip install --upgrade pip
        pip install cython buildozer

    - name: Configurar SDK y Aceptar Licencias
      run: |
        ANDROID_SDK="$HOME/.buildozer/android/platform/android-sdk"
        mkdir -p "$ANDROID_SDK/cmdline-tools/latest"
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-6514223_latest.zip -O /tmp/clt.zip
        unzip -q /tmp/clt.zip -d /tmp/clt_extracted
        mv /tmp/clt_extracted/bin "$ANDROID_SDK/cmdline-tools/latest/"
        mv /tmp/clt_extracted/lib "$ANDROID_SDK/cmdline-tools/latest/"
        rm -rf /tmp/clt.zip /tmp/clt_extracted
        export PATH=$PATH:$ANDROID_SDK/cmdline-tools/latest/bin
        yes | sdkmanager --licenses

    - name: Compilar APK
      run: |
        buildozer -v android debug

    - name: Subir el APK generado
      uses: actions/upload-artifact@v4
      with:
        name: paquete-apk
        path: bin/*.apk
